
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/customer?createDatabaseIfNotExist=true
    username: root
    password: 7879
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySqlDialect
      format_sql: true
    show-sql: true
  main:
    web-application-type: servlet